# Generated by Django 4.1.3 on 2022-11-08 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='released',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date released'),
            preserve_default=False,
        ),
    ]
