# Generated by Django 4.1.3 on 2022-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_album_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='released',
            field=models.IntegerField(help_text='Enter a four-digit year', verbose_name='year released'),
        ),
    ]
