# Generated by Django 4.1.3 on 2022-11-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_listen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='listen',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='listen',
            name='date',
            field=models.DateField(verbose_name='Listening Date'),
        ),
    ]
