# Generated by Django 4.1.3 on 2022-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_vibe_alter_listen_options_alter_listen_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='vibes',
            field=models.ManyToManyField(to='main_app.vibe'),
        ),
    ]
